version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/subham-deepsource/demo-go"
  goprivate = "github.com/deepsourcelabs/*"
  goproxy = "proxy.golang.org,direct"

[[transformers]]
name = "gofmt"
enabled = true
